# Generated by Django 2.2.7 on 2019-11-30 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTRAINEMENT', 'Entrainement'), ('MATCH', 'Match')], default='ENTRAINEMENT', max_length=50, verbose_name='Type')),
                ('event_date', models.DateField(verbose_name="Date de l'événement")),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': 'Événement',
            },
        ),
    ]
