# Generated by Django 2.2.7 on 2019-11-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTRAINEMENT', 'Entrainement'), ('MATCH', 'Match')], default='ENTRAINEMENT', max_length=50)),
                ('event_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
