# Generated by Django 2.2.7 on 2019-11-30 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attending', models.BooleanField(null=True, verbose_name='Est présent')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='core.Event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Présence',
            },
        ),
    ]
