# Generated by Django 2.2.7 on 2020-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191209_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_selected',
            field=models.BooleanField(null=True, verbose_name='Est sélectionné'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ENTRAINEMENT', 'Entrainement'), ('MATCH', 'Match'), ('MARCHE_GOURMANDE', 'Marche gourmande'), ('FETE_DE_LA_CERISE', 'Fête de la cerise'), ('JOURNEE_TRAVAIL', 'Journée travail'), ('AUTRES', 'Autres')], default='ENTRAINEMENT', max_length=50, verbose_name='Type'),
        ),
    ]
