# Generated by Django 2.2.7 on 2020-07-31 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('BAR', 'Bar'), ('EAU', 'Eau'), ('LAVAGE_CHASUBLES', 'Lavage chasubles'), ('VESTIAIRE', 'Vestiaire')], default=None, max_length=50, null=True, verbose_name='Type')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Attendance', verbose_name='Présence')),
            ],
            options={
                'verbose_name': 'Tâche',
            },
        ),
    ]
