# Generated by Django 2.2.7 on 2020-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200903_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_present_at_lunch',
            field=models.BooleanField(null=True, verbose_name='Vient au repas'),
        ),
    ]
